### ISSUE TITLE
Logstash cannot create new index after updating config and restarting logstash

### ISSUE THREAD

**Issue by iboware** [floragunncom/search-guard-ssl#25]
I am not sure if this is a search-guard or search-guard-ssl problem but it is for sure a search-guard* related problem. This scenario was working before installing and configuring search-guard. Here is the problem with repro steps:
1 - Restart  ElasticSearch
2 - Add a new input plugin config to logstash (added config details below).
3 - Start Logstash
4 - Logstash will create a new index for the new config
5 - Logstash will generate  bulk insert queries and add them to the new index.
6 - Stop logstash
7 - Repeat Step 2 and 3
8 - Logstash won't be able to create new index and will generate no error log about that.
9 - Logstash will try to insert bulk queries but it will result with a no index found error, because there is no created index in es.
10 - There will be unassigned shards in ES and cluster health will turn to red.
11 - Restart ElasticSearch node connected by logstash and logstash itself.  Index will be created and bulk queries will be restarted successfully, like the first time.

I don't know why it does not work without restarting es. Maybe something blocking the connection for some reason?

**Logstash Config**
```
input {
#elasticsearch test account
    couchdb_changes {
      db => "tenant1738"
      host => "server.mycouchdb.com"
      username=>'user'
      password=>'pass'
      sequence_path=> '/config-dir/sequences/tenant1738.seq'
      add_field => {
        "tenant" => "tenant1738"
      }
# here I add other couchdb_changes configurations, which works well without activating search-guard
  }
output {
 elasticsearch {
      document_id => "%{[@metadata][_id]}"
      document_type=> "%{[doc][type]}"
      hosts => ["elastic1.server.com"]
      index => "%{[tenant]}"
      ssl => true
      ssl_certificate_verification => true
      keystore => '/config-dir/web-keystore.jks'
      keystore_password => '*****'
      truststore => '/config-dir/web-truststore.jks'
      truststore_password => '******'
      user => logstash
      password => '***********'
     }
}
```

**ES Configuration:**

```
#SearchGuard
searchguard.ssl.http.enabled: true
searchguard.ssl.http.keystore_filepath: /usr/share/elasticsearch/config/web-keystore.jks
searchguard.ssl.http.keystore_password: '********/'
searchguard.ssl.http.truststore_filepath: /usr/share/elasticsearch/config/web-truststore.jks
searchguard.ssl.http.truststore_password: '*******/'
searchguard.ssl.transport.keystore_filepath: /usr/share/elasticsearch/config/elastic1-keystore.jks
searchguard.ssl.transport.keystore_password: '**********/'
searchguard.ssl.transport.truststore_filepath: /usr/share/elasticsearch/config/truststore.jks
searchguard.ssl.transport.truststore_password: '*********/'
searchguard.ssl.transport.enforce_hostname_verification: true
#searchguard.ssl.transport.resolve_hostname: true
searchguard.authcz.admin_dn:
  - "CN=admin,OU=client,O=client,L=Test,C=DE"
searchguard.ssl.transport.enable_openssl_if_available: true
searchguard.ssl.http.enable_openssl_if_available: true
```
**sg_roles.yml (partial)**

```
sg_logstash:
  cluster:
    - indices:admin/template/get
    - indices:admin/template/put
    - indices:data/write/bulk*
  indices:
    '*':
      '*':
        - indices:data/write/bulk*
        - indices:data/write/update*
        - indices:data/write/index*
        - indices:data/write/delete*
    'logstash-*':
      '*':
        - CRUD
        - CREATE_INDEX
    '*beat*':
      '*':
        - CRUD
        - CREATE_INDEX
```
**System Configuration:**

- Debian 8
- Oracle JDK 8
- OpenSSL 1.0.2h
- netty-tcnative-1.1.33.Fork17-linux-x86_64
- search-guard-ssl/2.3.3.11
- search-guard-2/2.3.3.0-rc1
- ES 2.3.3
- Kibana 4.5
